kind: CertificateSigningRequest
apiVersion: certificates.k8s.io/v1
metadata:
   name: user1
spec:
  groups:
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ2FUQ0NBVkVDQVFBd0pERVJNQThHQTFVRUF3d0laR1YyTFhWelpYSXhEekFOQmdOVkJBb01CbVJsZG05dwpjekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFQQmdsVm8yUXR0cWpCdEhYU0lLCjIwMEZrR0FseUZJUmpBNCtLdGtaejd5dTBMMXNaUGJMSHkzbWN4OHFVNEpsRlpQdDczcjYxd1RQQ3BzNXhCbFQKMkxqZXZvRzhvM3NjNi80SDltdUlIUHFLdVgzVjd1NWVRVTRHaWM0OW1SditaYjBwemtGOExSYVpkaDgrb0JyZQprT3RpOFRaUnMzV0JTZjNPNnBDZUg1ZWVaVDlVT1dYTGl3WnIvbEw0WmROU3hZaTROa3JpaHp3SDRwQ1hxZW0xCmg5RHdkZTFxUlJNSDNsa3dPWkJQZ1JzWmFyU1VsUXF2U0ZibDlTTE9yMVpZTDlJcFd4LzM4S2RtQTMxb2NuQzYKT0F1V1JhVUhBT1dmMWozOEZmR3JPRmcrU1YvSU9QUW5UVWxrUFRieE10N3hBNElwY1ZHcGRZN0xzOUFnR21jNgprTXNDQXdFQUFhQUFNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUJPVjd5d3RDTkpLUHVvL1N6dlhHUDBySjV6Cks0ejVPYk9yWEY4K1QxRXRCcHVDV0xBTWw1NC9EWCtOa2dMbGZacGdRVGpUMzJWbmdVVVpIeEc0elFTemxZcG8KRE5FR3VuYUJMOGxQZVNnb3g0L3p2MG5YcVFOK0VDa2tiNnZwNkgrQUxwME91TWRrZ3JWcUlDNlFaZGttUmJLNwpsVnp4MTZRUXZ2Z2dod3RxaFhia1pvYXFWZnJJbmxaay91SEYrdFA0ZGZ4UGNLZG51aEZxNU42YXhDWjBYTmYvCnUxWkQ1UFk1aU0vazNQVkdjQldiSnJLdDZVVzVDeXN2V2NKQjZ6c0g1OEk3U1BrUFlPeUxCd2Z3NHJOeWdTYlEKQTl2SEFqK1J5c3c0d0lldlorTHQrdmZpNHI5QXJRTjZyZ0hOTnZWMVhmNlVXTjVyQU92Mm1RdUZpUXk1Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=

  signerName: kubernetes.io/kube-apiserver-client
  #expirationSeconds: 86400
  usages:
  - client auth


# openssl genrsa -out user1.key 2048
# openssl req -config csr.conf -new -key user1.key -nodes -out user1.csr
# cat user1.csr | base64 | tr -d '\n'
# kubectl apply -f csr.yml
# kubectl get csr ; kubectl certificate approve prod-user
# kubectl get csr prod-user -o jsonpath="{.status.certificate}" | base64 --decode > user1.crt
# modify kubeconfig with 