apiVersion: v1
kind: Config
clusters:
- name: my-cluster
  cluster:
    server: https://cluster.example.com
    certificate-authority-data: <base64-encoded-CA-certificate>
contexts:
- name: my-context
  context:
    cluster: my-cluster
    user: my-user
users:
- name: my-user
  user:
    client-certificate-data: <base64-encoded-client-certificate>
    client-key-data: <base64-encoded-client-key>
current-context: my-context
